name: eppnad
channels:
  - conda-forge
  - defaults

dependencies:
  # Core, Data Science, and ML
  - python=3.10
  - tensorflow
  - pandas
  - scikit-learn
  - numpy
  - pynvml
  - pymongo      
  
  # Plotting & Visualization
  - matplotlib
  - seaborn

  # Development & Testing Tools
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-timeout
  - black 

  # Pip-specific packages (only what's not on conda)
  - pip
  - pip:
    - pyJoules==0.5.1
    - pyRAPL==0.2.3.1