# This is a GitHub Actions workflow file that defines your CI process.
# It automates the testing of your code on every push and pull request.

name: Continuous Integration

# 1. TRIGGERS: This section defines when the workflow will run.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. JOBS: A workflow run is made up of one or more jobs.
jobs:
  # The "build-and-test" job runs all our checks.
  build-and-test:
    runs-on: ubuntu-latest

    # 3. STEPS: A job contains a sequence of tasks called steps.
    steps:
      # Step 1: Checks out your repository's code.
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Sets up the Conda environment.
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          environment-file: environment.yml
          activate-environment: eppnad

      # Step 3: NEW! Install the local eppnad project into the environment.
      # This makes the 'eppnad' module importable for the tests.
      - name: Install project
        shell: bash -l {0}
        run: pip install -e .

      # Step 4: Runs the test suite using pytest.
      - name: Run tests with pytest
        shell: bash -l {0}
        run: pytest -m "not rapl"